name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        logout: true
    - name: Docker Buildx
      # You may pin to the exact commit or the version.
      # uses: crazy-max/ghaction-docker-buildx@126d331dc69f4a1aa02452e374835e6a5d565613
      uses: crazy-max/ghaction-docker-buildx@v3.3.1
      with:
        # Buildx version. Example: v0.3.0
        buildx-version: latest
        # QEMU static binaries Docker image version. Example: 4.2.0-7
        qemu-version: latest
        
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker buildx build --push --platform linux/arm64,linux/amd64 --tag mikeybrien/ecobee-exporter:latest .

      
   
